# Generated by Django 4.2 for credentials app — ASR29
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=64, unique=True)),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('ambiente', models.CharField(
                    choices=[('dev', 'Desarrollo'), ('test', 'Pruebas'), ('prod', 'Producción')],
                    db_index=True,
                    max_length=10,
                )),
                ('provider', models.CharField(
                    choices=[('aws', 'AWS'), ('gcp', 'GCP')],
                    max_length=10,
                )),
                ('encrypted_key', models.BinaryField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'credentials'},
        ),
        migrations.CreateModel(
            name='CredentialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('geo_country', models.CharField(max_length=2)),
                ('endpoint', models.CharField(max_length=128)),
                ('success', models.BooleanField()),
                ('credential', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='usages',
                    to='credentials.credential',
                )),
            ],
            options={'db_table': 'credential_usages'},
        ),
        migrations.CreateModel(
            name='CredentialUsageHistory',
            fields=[
                ('client_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('typical_countries', models.JSONField()),
                ('typical_hour_start', models.IntegerField()),
                ('typical_hour_end', models.IntegerField()),
                ('avg_requests_per_min', models.FloatField()),
                ('stddev_requests', models.FloatField()),
            ],
            options={'db_table': 'credential_usage_history'},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(
                    choices=[
                        ('ANOMALY', 'Anomalía detectada'),
                        ('REVOCATION', 'Credencial revocada'),
                        ('NOTIFICATION', 'Notificación enviada'),
                    ],
                    max_length=32,
                )),
                ('credential_id', models.CharField(max_length=64)),
                ('details', models.JSONField()),
            ],
            options={'db_table': 'audit_logs', 'ordering': ['-timestamp']},
        ),
    ]
